name: DIY-JDCloud-LibWrt

on:
  workflow_dispatch:
    inputs:
      REPO_BRANCH:
        options:
          - 'main-nss'
          - '25.12-nss'
        description: '源码分支'
        required: true
        default: 'main-nss'
        type: choice
      WRT_NAME:
        description: '固件名称'
        required: false
        default: 'Roc'
        type: string
      WRT_SSID:
        description: 'WIfi-SSID'
        required: false
        default: 'CHEN'
        type: string
      WRT_WORD:
        description: 'Wifi密码'
        required: false
        default: '12345678'
        type: string
      WRT_IP: 
        description: '路由管理IP'
        required: false
        default: '192.168.9.1'
        type: string
        
  workflow_call:
  # schedule:
  #   - cron: "0 18 * * *"

env:
  # REPO_BRANCH: ${{inputs.REPO_BRANCH}}
  WRT_NAME: ${{inputs.WRT_NAME}}
  WRT_SSID: ${{inputs.WRT_SSID}}
  WRT_WORD: ${{inputs.WRT_WORD}}
  WRT_IP: ${{inputs.WRT_IP}}
  
permissions:
  contents: write
  actions: write

jobs:
  Build:
    uses: ./.github/workflows/DIY-Build-OpenWrt.yml
    permissions:
      contents: write
      actions: write
    with:
      repo_url: https://github.com/laipeng668/openwrt-6.x.git
      repo_branch: ${{inputs.REPO_BRANCH}}
      config_file: configs/DIY-JDCloud.config
      firmware_tag: IPQ60XX
      kernel_file: kernel-6.12
      artifact_prefix: IPQ60XX
      manifest_file: libwrt-qualcommax-ipq60xx.manifest
      release_summary: >-
        这是开启全功能NSS的6.12内核固件，默认主题为Aurora；该固件在ImmortalWrt的基础上，添加了额外的软件包cpufreq、ddns、upnp、wol、samba4、vlmcsd、autoreboot、uhttpd、frps、frpc、diskman、hd-idle、acme、wireguard、watchcat、3cat、passwall，并添加了若干工具，具体详见DIY-JDCloud.config和DIY-General.config。
