name: JDCloud-NoWiFi-ImmortalWrt

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: "0 18 * * *"

permissions:
  contents: read
  actions: read

jobs:
  Build:
    uses: ./.github/workflows/Build-OpenWrt.yml
    permissions:
      contents: write
      actions: write
    with:
      repo_url: https://github.com/laipeng668/immortalwrt.git
      repo_branch: openwrt-25.12
      config_file: configs/JDCloud.NoWiFi.config
      firmware_tag: JDCloud
      kernel_file: kernel-6.12
      artifact_prefix: Arthur.Athena.Taiyi.NoWiFi
      manifest_file: immortalwrt-qualcommax-ipq60xx.manifest
      rename_qualcommax_to_nowifi: true
      release_summary: >-
        这是开启全功能NSS的6.12内核固件，默认主题为Aurora；该固件在ImmortalWrt的基础上，添加了额外的软件包cpufreq、ddns、upnp、wol、samba4、vlmcsd、aria2、autoreboot、uhttpd、frps、frpc、diskman、hd-idle、acme、openlist2、wireguard、watchcat、3cat、passwall、gecoosac，并添加了若干工具，具体详见JDCloud.config(NoWiFi.config)和General.config。
